### ISSUE TITLE
Environment variables?

### ISSUE THREAD

**Issue by SteveEdson** [anystack-sh/porter#27]
Is it possible to set env variables? My yml looks like this:

```yaml
services:
 - name: Router
   command: "SANDBOX=true ./router -c router.yaml -s supergraph.graphql"
```

But I get the error:

```
➜ porter status
+----------------+--------------------------------------+---------+-----------------------------------+
| App            | Process                              | Status  | Description                       |
+----------------+--------------------------------------+---------+-----------------------------------+
| example        | example-router                       | BACKOFF | can't find command 'SANDBOX=true' |
|
+----------------+--------------------------------------+---------+-----------------------------------+
```

**Comment by PhiloNL** [comment]
Hmm, maybe try `export SANDBOX=true && ./router -c router.yaml -s supergraph.graphql`

**Comment by SteveEdson** [comment]
Just get the error `can't find command 'export'` unfortunately

**Comment by PhiloNL** [comment]
@SteveEdson thanks for letting me know, I've added a new option in v0.0.10 to override environment variables:

```yaml
  - name: Vite
    directory: Users/developer/anystack/front-end
    command: npm run dev
    environment:
        - FOO=BAR
```

Let me know if that works
